config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :conversations do
    resources :messages
  end

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

  resources :poems, only: [:index, :show]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    #orderで新らしいのがくるように並び替え where(read: false)で未読通知のみ表示
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  #2016-08-23 05:57:47のように表示されるので、日本用に変更
  def posted_time(time)
  time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <h2>お知らせ内容一覧</h2>
    <p>ブログのリンクをクリックすると、未読は解除されます。</p>
    <ul>
      <% @notifications.each do |notification| %>
      <hr>
      <li>
        <p>
          <%= notification.comment.user.try(:name) %>さんが、<br>
          あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
        </p>
        <p>
          <%= notification.created_at %>
          <% if notification.read == false %>
          <span><%= "状態：未読" %></span>
          <% end %>
        </p>
      </li>
      <% end %>
    </ul>
  </div>
</div>